config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'pages#home'
resources :cocktails, only: [:index, :show, :new, :create ] do
resources :doses, only: [:new, :create]
end
resources :doses, only: :destroy
resources :cocktails, only: :destroy, as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
     if @cocktail.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end




  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

def new
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose = Dose.new
end

def create
  @dose = Dose.new(dose_params)
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose.cocktail = @cocktail
  @dose.save
  if @dose.save
  redirect_to cocktail_path(params[:cocktail_id])
  else
    render :new
  end
end

def destroy
  @dose = Dose.find(params[:id])
  @dose.destroy
  redirect_to cocktail_path(@dose.cocktail)
end

private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/index.html.erb
<div class="main-container">
  <div class="container">
    <div class="first">
      <h1>Cocktails list :</h1>
    </div>
    <div class="cards">
      <% @cocktails.each do |cocktail| %>

          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/1600x900/?cocktail-<%=cocktail.name%>')">
          <p>
            <%= link_to '<i class="fas fa-trash"></i>'.html_safe, delete_path(cocktail), method: :delete, data: { confirm: 'Do you REALLY want to destroy this wonderful cocktail?'}, class: 'card-remove-link'%>
          </p>
          <br>
          <%= link_to cocktail.name.capitalize, cocktail_path(cocktail.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="main-container">
  <div class="small-container">
    <h1>Add a new Cocktail</h1>
      <%= simple_form_for [@cocktail] do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
        </div>
        <%= f.button :submit,'Add to Mister Cocktail', class: 'bouton' %>

      <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="main-container">
  <div class="container">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/1600x900/?cocktail-<%=@cocktail.name%>')">
      <h1><%= @cocktail.name.capitalize %></h1>
    </div>
    <h1>Ingredients (<%= @cocktail.doses.count %>): </h1>
      <% @cocktail.doses.each do |dose| %>
        <div class="card-dose">
          <img src="https://source.unsplash.com/400x300/?ingredient-<%=dose.ingredient.name%>" />
          <div class="card-dose-infos">
            <h2> <%= dose.ingredient.name %></h2>
            <p>Quantity : <%= dose.description %></p>
            <br>
            <%= link_to '<i class="fas fa-trash"></i>'.html_safe, dose_path(dose), method: :delete, data: { confirm: 'are you sure?'} %>
          </div>
        </div>
      <% end %>
      <%= link_to "Add ingredients", new_cocktail_dose_path(@cocktail), class: 'btn btn-primary pink mt-5'%>
    </div>
</div>

app/views/doses/new.html.erb
<div class="main-container">
  <div class="small-container">
    <h1>Add ingredients to your <%= @cocktail.name %></h1>
       <%= simple_form_for [@cocktail, @dose] do |f|%>
        <div class="form-inputs">
          <%= f.input :description %>
          <%= f.association :ingredient %>
        </div>
        <div>
          <%= f.button :submit, "Add ingredient", class: 'bouton' %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
  <h1>
    <span id="banner-typed-text"></span>
  </h1>
</div>

app/views/shared/_navbar.html.erb
<!--Navbar-->
<nav class="navbar navbar-light white lighten-4">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="/cocktails">  <%= image_tag "logo.png", alt: "logo", height: 40 %> </a>

  <!-- Collapse button -->
  <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-pink-text"><i
        class="fas fa-bars fa-1x"></i></span></button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent1">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Say hello to Tom!", pages_home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Cocktails list", cocktails_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add a new cocktail", new_cocktail_path, class: "nav-link" %>
      </li>
    </ul>
    <!-- Links -->

  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->